name: emote
version: '1.0.1'
license: GPL-3.0+
summary: Modern emoji picker built on GTK3
description: |
  Emote is a simple emoji picker that is launched with a keyboard shortcut and
  copies the selected emoji to the clipboard. Emote is lightweight and stays
  out of your way.
icon: snap/gui/emote.svg

base: core18
grade: stable # or devel. Must be 'stable' to release into candidate/stable channels
confinement: strict # or devmode

parts:
  emote:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - wheel
      - pygobject
      - setuptools
    build-packages:
      - python3-setuptools
      - python3-xlib
      - pkg-config
    build-packages:
      - libgirepository1.0-dev
    stage-packages:
      - libcairo-gobject2
      - libcairo2
      - libfontconfig1
      - libfreetype6
      - libgirepository-1.0-1
      - libpixman-1-0
      - libpng16-16
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxrender1
      - libkeybinder-3.0-0
      - gir1.2-keybinder-3.0
      - python3-distutils-extra
      - sound-theme-freedesktop
      - pulseaudio-utils
      - python3-gi
      - gir1.2-unity-5.0
      - gir1.2-notify-0.7
      - gir1.2-gtk-3.0
      - gir1.2-pango-1.0
      - appmenu-gtk2-module
      - appmenu-gtk3-module
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
  static:
    plugin: dump
    source: static/
    organize:
      '*': static/
  desktop-resources:
    plugin: dump
    source: snap/gui/
    organize:
      emote.desktop: usr/share/applications/emote.desktop
      emote.svg: usr/share/icons/emote.svg
    stage:
      - usr/share/applications/emote.desktop
      - usr/share/icons/emote.svg

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.tomjwatson.Emote


apps:
  emote:
    command: desktop-launch $SNAP/static/setup-autostart $SNAP/bin/emote
    desktop: usr/share/applications/emote.desktop
    extensions: [gnome-3-28]
    slots: [dbus-daemon]
    common-id: com.tomjwatson.Emote
    autostart: emote.desktop
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
